const OWN_ACCOUNT_TYPES = {
    FETCH: 'ACCOUNT_FETCH',
    FETCH_ERROR: 'ACCOUNT_FETCH_ERROR',
    FETCH_SUCCESS: 'ACCOUNT_FETCH_SUCCESS',
    FETCH_LOGOUT_SUCCESS: 'ACCOUNT_FETCH_LOGOUT_SUCCESS',
    FETCH_AUTHENTICATED_SUCCESS: 'ACCOUNT_FETCH_AUTHENTICATED_SUCCESS'
}

const NOTOWN_ACCOUNT_TYPES = {
    FETCH: 'ACCOUNT_FETCH',
    FETCH_ERROR: 'ACCOUNT_FETCH_ERROR',
    FETCH_SUCCESS: 'ACCOUNT_FETCH_SUCCESS',
    FETCH_LOGOUT_SUCCESS: 'ACCOUNT_FETCH_LOGOUT_SUCCESS',
    FETCH_AUTHENTICATED_SUCCESS: 'ACCOUNT_FETCH_AUTHENTICATED_SUCCESS'
}

const COMPANY_TYPES = {
    FETCH: 'COMPANY_FETCH',
    FETCH_ERROR: 'COMPANY_FETCH_ERROR',
    FETCH_SUCCESS: 'COMPANY_FETCH_SUCCESS',
}

const DONATION_TYPES = {
    FETCH: 'DONATION_FETCH',
    FETCH_ERROR: 'DONATION_FETCH_ERROR',
    FETCH_SUCCESS: 'DONATION_FETCH_SUCCESS',
}

const LOAN_TYPES = {
    FETCH: 'LOAN_FETCH',
    FETCH_ERROR: 'LOAN_FETCH_ERROR',
    FETCH_SUCCESS: 'LOAN_FETCH_SUCCESS',
}

const INVESTOR_TYPES = {
    FETCH: 'ACCOUNT_FETCH',
    FETCH_ERROR: 'ACCOUNT_FETCH_ERROR',
    FETCH_SUCCESS: 'ACCOUNT_FETCH_SUCCESS',
}

export {
    COMPANY_TYPES,
    DONATION_TYPES,
    INVESTOR_TYPES,
    LOAN_TYPES,
    NOTOWN_ACCOUNT_TYPES,
    OWN_ACCOUNT_TYPES,
}